name: "LOCAL CALENDAR AND POETRY"
version: 'latest-2024092512'
slug: 'calendar_poetry'
codenotary: wghaos@163.com
description: '它是本地日历和古诗词相结合的接口'
image: wghaos/{arch}-calendar-poetry
url: https://github.com/waxgourd-ha/waxgourd-addons
init: false
arch:
  - aarch64
  - amd64
ports:
  80/tcp: 13001
  5000/tcp: 13002
apparmor: true
boot: manual
