name: Get HACS
version: "1.3.1"
slug: get
description: 获取家庭助理HACS的最简单方法
startup: once
boot: manual
url: "https://github.com/hacs/addons/tree/main/get"
image: wghaos/addons-get-hacs
# image: ghcr.io/hacs/{arch}-addon-get
arch:
  - aarch64
  - amd64
init: false
schema:
  channel: list(current|development)?
map:
  - homeassistant_config:rw
